version: "3"
services:
  nginx:
    depends_on: ['wordpress']
    build:
      context: requirements/nginx
    container_name: nginx
    # env_file: ".env"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wp:/var/www/wordpress
    networks:
      - network
  wordpress:
    depends_on: ['mysql']
    env_file: ".env"
    build:
      args:
        WP_DB_NAME: ${WP_DB_NAME}
        ADMIN_WP_USER: ${ADMIN_WP_USER}
        ADMIN_WP_PASS: ${ADMIN_WP_PASS}
      context: requirements/wordpress
    container_name: wordpress
    env_file: ".env"
    volumes:
      - wp:/var/www/wordpress
    networks:
      - network
  mysql:
    env_file: ".env"
    build:
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        WP_DB_NAME: ${WP_DB_NAME}
        ADMIN_WP_USER: ${ADMIN_WP_USER}
        ADMIN_WP_PASS: ${ADMIN_WP_PASS}
      context: requirements/mysql
    container_name: mysql
    env_file: ".env"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - network
volumes:
  mysql:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mysql
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
networks:
  network:
